// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $auth_callback from "./routes/auth/callback.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_oauth from "./routes/auth/oauth.tsx";
import * as $index from "./routes/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/auth/callback.tsx": $auth_callback,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/oauth.tsx": $auth_oauth,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
